---
  name: Build and test
  on:
    push:
      branches:
        - master
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.9.0'
        - name: Install dependencies
          run: yarn install
        - name: Lint the code
          run: yarn lint
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            tags: tommavl/webapp:latest
            push: true
  